parserOptions:
  ecmaVersion: 11
  sourceType: module

env:
  es2020: true
  browser: true

extends:
  - 'htmlacademy/es6'

plugins:
  - import

rules:
  no-console: 0
  import/extensions: 0
  import/prefer-default-export: 0
  class-methods-use-this: 0
